# Generated by Django 5.1.5 on 2025-02-28 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_class", models.CharField(max_length=50)),
                ("confidence", models.FloatField()),
                ("volume", models.FloatField(default=0.0)),
                ("weight", models.FloatField(default=0.0)),
                ("bbox", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(default="0000000000", max_length=15)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Car", "Car"),
                            ("Small Van", "Small Van"),
                            ("Large Van", "Large Van"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "mover_type",
                    models.CharField(
                        choices=[
                            ("Pro Mover", "Professional Mover"),
                            ("Mover", "Simple Mover"),
                            ("Box Packer", "Box Packer"),
                            ("Driver with Help", "Driver with Help"),
                            ("Driver without Help", "Driver without Help"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("payment_info", models.CharField(max_length=255)),
                (
                    "driving_license",
                    models.ImageField(blank=True, null=True, upload_to="licenses/"),
                ),
                ("carrying_capacity", models.IntegerField(blank=True, null=True)),
                (
                    "identification_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("has_vehicle", models.BooleanField(default=False)),
                ("has_mover_certification", models.BooleanField(default=False)),
                (
                    "mover_certification_document",
                    models.ImageField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("origin_floor", models.IntegerField(blank=True, null=True)),
                ("destination_floor", models.IntegerField(blank=True, null=True)),
                ("has_elevator", models.BooleanField(default=False)),
                ("need_pro_mover", models.BooleanField(default=False)),
                ("need_box_packer", models.BooleanField(default=False)),
                ("move_date", models.DateTimeField()),
                ("origin_location", models.CharField(max_length=100)),
                ("destination_location", models.CharField(max_length=100)),
                ("total_volume", models.FloatField(default=0)),
                ("total_weight", models.FloatField(default=0)),
                ("status", models.CharField(default="Pending", max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.customer"
                    ),
                ),
                (
                    "items_detected",
                    models.ManyToManyField(
                        blank=True, related_name="orders", to="users.detecteditem"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detecteditem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detected_items",
                to="users.order",
            ),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.order"
                    ),
                ),
            ],
        ),
    ]
