# Generated by Django 5.1.5 on 2025-03-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='move_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
