# Generated by Django 5.1.5 on 2025-02-04 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mover',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='mover',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mover',
            name='vehicle_type',
            field=models.CharField(default='Truck', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mover',
            name='mover_type',
            field=models.CharField(choices=[('Pro Mover', 'Professional Mover'), ('Mover', 'Simple Mover'), ('Box Packer', 'Box Packer'), ('Driver with Help', 'Driver with Help'), ('Driver without Help', 'Driver without Help')], max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('origin_floor', models.IntegerField(blank=True, null=True)),
                ('destination_floor', models.IntegerField(blank=True, null=True)),
                ('has_elevator', models.BooleanField(default=False)),
                ('need_pro_mover', models.BooleanField(default=False)),
                ('need_box_packer', models.BooleanField(default=False)),
                ('move_date', models.DateTimeField()),
                ('origin_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('total_volume', models.FloatField(default=0)),
                ('total_weight', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_class', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('volume', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('bbox', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_detected', to='users.order')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='photos/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.order')),
            ],
        ),
    ]
