# Generated by Django 5.1.5 on 2025-02-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customer_location_remove_customer_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='payment_info',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
