# Generated by Django 5.1.5 on 2025-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_move_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='move_date',
            field=models.DateField(),
        ),
    ]
