# Generated by Django 5.1.5 on 2025-02-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mover_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mover',
            name='payment_info',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
