# Generated by Django 5.1.5 on 2025-02-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_mover_payment_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='mover',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='mover',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mover',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
