# Generated by Django 5.1.5 on 2025-03-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_destination_lat_order_destination_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destination_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destination_lng',
        ),
        migrations.RemoveField(
            model_name='order',
            name='origin_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='origin_lng',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='move_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.order'),
        ),
    ]
