# Generated by Django 5.1.5 on 2025-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_name_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mover',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Small Van', 'Small Van'), ('Large Van', 'Large Van')], max_length=100),
        ),
    ]
