# Generated by Django 5.1.5 on 2025-03-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_created_at_order_destination_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/processed/'),
        ),
    ]
