# Generated by Django 5.1.5 on 2025-02-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customer_id_alter_detecteditem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mover',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mover',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='mover',
            name='carrying_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mover',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='mover',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mover',
            name='payment_info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mover',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mover',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Small Van', 'Small Van'), ('Large Van', 'Large Van')], max_length=100, null=True),
        ),
    ]
