# Generated by Django 5.1.5 on 2025-02-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_mover_email_remove_mover_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='has_mover_certification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mover',
            name='has_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mover',
            name='identification_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mover',
            name='mover_certification_document',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='order',
            name='items_detected',
            field=models.ManyToManyField(blank=True, related_name='orders', to='users.detecteditem'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='detecteditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_items', to='users.order'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.order'),
        ),
    ]
