# Generated by Django 5.1.5 on 2025-03-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_processedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='order_bids', to='users.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_list', to='users.order'),
        ),
    ]
