# volume_weight_estimates.py

VOLUME_WEIGHT_ESTIMATES = {
    # Living Room
    'sofa/couch': {'volume': 3.0, 'weight': 50},
    'recliner chair': {'volume': 1.5, 'weight': 30},
    'armchair': {'volume': 1.2, 'weight': 25},
    'coffee table': {'volume': 1.0, 'weight': 20},
    'end tables/side tables': {'volume': 0.8, 'weight': 15},
    'tv stand/entertainment center': {'volume': 1.2, 'weight': 40},
    'tv': {'volume': 0.5, 'weight': 15},
    'bookshelves': {'volume': 1.0, 'weight': 35},
    'lamps': {'volume': 0.2, 'weight': 5},
    'rugs/carpets': {'volume': 0.1, 'weight': 10},
    'curtains/blinds': {'volume': 0.05, 'weight': 3},
    'wall art/paintings': {'volume': 0.2, 'weight': 5},
    'shelving units': {'volume': 1.5, 'weight': 30},
    'entertainment equipment': {'volume': 0.5, 'weight': 20},
    'throw pillows': {'volume': 0.1, 'weight': 2},
    'storage ottomans': {'volume': 0.6, 'weight': 10},
    'blankets/throws': {'volume': 0.3, 'weight': 5},

    # Bedroom
    'bed': {'volume': 2.5, 'weight': 60},
    'nightstands': {'volume': 0.8, 'weight': 15},
    'dresser/chest of drawers': {'volume': 1.5, 'weight': 45},
    'wardrobe/closet': {'volume': 2.0, 'weight': 70},
    'bedding': {'volume': 0.4, 'weight': 8},
    'lamps': {'volume': 0.2, 'weight': 5},
    'mirror': {'volume': 0.3, 'weight': 10},
    'clothes hangers': {'volume': 0.05, 'weight': 2},
    'desk': {'volume': 1.5, 'weight': 40},
    'chairs': {'volume': 0.5, 'weight': 10},
    'laundry basket/bin': {'volume': 0.7, 'weight': 5},
    'chest': {'volume': 1.0, 'weight': 25},
    'jewelry box': {'volume': 0.1, 'weight': 2},
    'footstool/ottoman': {'volume': 0.6, 'weight': 10},
    'bookshelves': {'volume': 1.0, 'weight': 35},
    'storage bins/boxes': {'volume': 0.5, 'weight': 8},
    'toys': {'volume': 0.3, 'weight': 5},

    # Kitchen
    'dining table & chairs': {'volume': 2.5, 'weight': 60},
    'bar stools': {'volume': 0.7, 'weight': 12},
    'refrigerator': {'volume': 2.0, 'weight': 80},
    'microwave': {'volume': 0.3, 'weight': 12},
    'dishwasher': {'volume': 1.0, 'weight': 45},
    'stove/oven': {'volume': 1.5, 'weight': 70},
    'range hood': {'volume': 0.4, 'weight': 15},
    'coffee maker': {'volume': 0.2, 'weight': 5},
    'blender/food processor': {'volume': 0.3, 'weight': 6},
    'toaster/toaster oven': {'volume': 0.3, 'weight': 5},
    'stand mixer': {'volume': 0.4, 'weight': 10},
    'cookware': {'volume': 0.5, 'weight': 20},
    'cutlery/knife block': {'volume': 0.2, 'weight': 5},
    'cups, mugs, glassware': {'volume': 0.4, 'weight': 8},
    'dishes': {'volume': 0.5, 'weight': 10},
    'utensils': {'volume': 0.3, 'weight': 6},
    'storage containers': {'volume': 0.5, 'weight': 8},
    'pantry items': {'volume': 1.0, 'weight': 20},
    'trash cans/recycling bins': {'volume': 0.8, 'weight': 15},
    'spices, seasoning racks': {'volume': 0.2, 'weight': 5},
    'wine rack': {'volume': 0.5, 'weight': 10},
    'trash bags': {'volume': 0.1, 'weight': 2},
    'kitchen towels': {'volume': 0.1, 'weight': 1},
    'cleaning supplies': {'volume': 0.5, 'weight': 8},
    'kitchen shelving units': {'volume': 1.5, 'weight': 30},
    'wall art': {'volume': 0.2, 'weight': 5},
    'curtains/blinds': {'volume': 0.05, 'weight': 3},

    # Dining Room
    'dining table': {'volume': 2.0, 'weight': 50},
    'dining chairs': {'volume': 0.5, 'weight': 10},
    'buffet/sideboard': {'volume': 1.5, 'weight': 40},
    'china cabinet': {'volume': 2.0, 'weight': 60},
    'bar cart': {'volume': 1.0, 'weight': 25},
    'serving dishes/platters': {'volume': 0.5, 'weight': 10},
    'candles/candle holders': {'volume': 0.2, 'weight': 3},
    'table linens': {'volume': 0.3, 'weight': 5},
    'glassware': {'volume': 0.4, 'weight': 8},
    'side tables': {'volume': 0.8, 'weight': 15},
    'artwork/wall décor': {'volume': 0.2, 'weight': 5},
    'storage (cabinets, shelves)': {'volume': 2.0, 'weight': 50},

    # Home Office
    'desk': {'volume': 1.5, 'weight': 40},
    'office chair': {'volume': 0.7, 'weight': 15},
    'bookshelves/storage shelves': {'volume': 1.2, 'weight': 35},
    'filing cabinets': {'volume': 1.0, 'weight': 30},
    'computer': {'volume': 0.5, 'weight': 10},
    'monitors': {'volume': 0.3, 'weight': 8},
    'keyboard, mouse': {'volume': 0.1, 'weight': 2},
    'printer': {'volume': 0.4, 'weight': 12},
    'paper shredder': {'volume': 0.3, 'weight': 8},
    'desk lamp': {'volume': 0.2, 'weight': 4},
    'task chair': {'volume': 0.7, 'weight': 15},
    'cable management tools': {'volume': 0.1, 'weight': 2},
    'wall art/inspirational quotes': {'volume': 0.2, 'weight': 5},
    'organizers': {'volume': 0.3, 'weight': 6},
    'whiteboard/pinboard': {'volume': 0.5, 'weight': 10},
    'books': {'volume': 0.4, 'weight': 10},

    # Bathroom
    'shower curtain/screen': {'volume': 0.2, 'weight': 5},
    'bathtub': {'volume': 2.0, 'weight': 70},
    'toilet': {'volume': 0.8, 'weight': 30},
    'sink/cabinet': {'volume': 1.0, 'weight': 40},
    'bathroom rugs': {'volume': 0.3, 'weight': 5},
    'towels': {'volume': 0.3, 'weight': 5},
    'toiletries': {'volume': 0.2, 'weight': 5},
    'toothbrush/toothpaste': {'volume': 0.1, 'weight': 2},
    'mirrors': {'volume': 0.3, 'weight': 10},
    'medicine cabinet': {'volume': 0.5, 'weight': 15},
    'storage baskets': {'volume': 0.4, 'weight': 8},
    'shower caddy': {'volume': 0.3, 'weight': 5},
    'trash can': {'volume': 0.4, 'weight': 8},
    'hairdryer': {'volume': 0.2, 'weight': 3},
    'towel rack': {'volume': 0.5, 'weight': 12},
    'bathroom shelves': {'volume': 1.0, 'weight': 20},
    'linen closet': {'volume': 1.5, 'weight': 35},

    # Laundry Room
    'washing machine': {'volume': 2.0, 'weight': 75},
    'dryer': {'volume': 2.0, 'weight': 70},
    'laundry basket/bin': {'volume': 0.7, 'weight': 5},
    'ironing board/iron': {'volume': 0.8, 'weight': 10},
    'laundry detergent': {'volume': 0.5, 'weight': 8},
    'cleaning supplies': {'volume': 0.5, 'weight': 8},
    'drying rack': {'volume': 1.0, 'weight': 15},
    'storage shelves': {'volume': 1.5, 'weight': 30},
    'vacuum cleaner': {'volume': 1.0, 'weight': 15},
    'shoe rack': {'volume': 1.0, 'weight': 20},
    'clothing hangers': {'volume': 0.1, 'weight': 2},

    # Outdoor/Patio
    'outdoor furniture': {'volume': 3.0, 'weight': 50},
    'bbq grill': {'volume': 2.0, 'weight': 65},
    'garden tools': {'volume': 1.0, 'weight': 15},
    'lawnmower': {'volume': 2.5, 'weight': 90},
    'umbrella': {'volume': 1.5, 'weight': 10},
    'outdoor rugs': {'volume': 0.5, 'weight': 8},
    'hammock': {'volume': 1.5, 'weight': 10},
    'potted plants': {'volume': 0.8, 'weight': 20},
    'outdoor lighting': {'volume': 0.5, 'weight': 5},
    'swing': {'volume': 2.0, 'weight': 50},
    'gazebo/tent': {'volume': 3.5, 'weight': 100},
    'garden bench': {'volume': 2.0, 'weight': 40},
    'storage shed': {'volume': 4.0, 'weight': 150},
    'outdoor heater': {'volume': 2.0, 'weight': 70},

    # Miscellaneous
    'exercise equipment': {'volume': 3.0, 'weight': 100},
    'musical instruments': {'volume': 4.0, 'weight': 300},
    'clocks': {'volume': 0.3, 'weight': 5},
    'toys': {'volume': 0.5, 'weight': 8},
    'holiday decorations': {'volume': 1.0, 'weight': 15},
    'luggage': {'volume': 0.8, 'weight': 10},
    'fan': {'volume': 0.4, 'weight': 5},
    'space heaters': {'volume': 0.5, 'weight': 10},
    'dehumidifier/humidifier': {'volume': 0.8, 'weight': 20},
    'air conditioner': {'volume': 1.0, 'weight': 40},
    'bicycles': {'volume': 2.0, 'weight': 15},
    'sporting equipment': {'volume': 2.5, 'weight': 25},

    # Optional/High-Value Items
    'antiques': {'volume': 1.5, 'weight': 30},
    'art pieces': {'volume': 1.0, 'weight': 20},
    'collectibles': {'volume': 0.5, 'weight': 10},
    'jewelry boxes': {'volume': 0.2, 'weight': 3},
    'luxury items': {'volume': 2.0, 'weight': 40},
}
